version: '2'
services:

  web:
    container_name: wa-commerce-api
    build: docker/dev
    ports:
      - "3001:3000"
      - "3229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database

  database:
    container_name: wa-commerce-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=waCommerce
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123mudar
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "adm@waproject.com.br"
      PGADMIN_DEFAULT_PASSWORD: "123mudar"
    ports:
      - "16543:80"
